// flow-typed signature: 88683a2bc9703350c9ddc9475609b3ce
// flow-typed version: <<STUB>>/eslint-config-lystable_v^6.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-lystable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-lystable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-lystable/__tests__/test-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-lystable/__tests__/test-rules.js' {
  declare module.exports: $Exports<'eslint-config-lystable/__tests__/test-rules'>;
}
declare module 'eslint-config-lystable/index' {
  declare module.exports: $Exports<'eslint-config-lystable'>;
}
declare module 'eslint-config-lystable/index.js' {
  declare module.exports: $Exports<'eslint-config-lystable'>;
}
