// flow-typed signature: 1418bd7adf2d4b1de7480baa1dbdb5d2
// flow-typed version: <<STUB>>/jsdom_v7.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsdom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsdom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsdom/lib/jsdom' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/default-stylesheet' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/documentAdapter' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/documentfeatures' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/domtohtml' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/history' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/htmltodom' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/location' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/not-implemented' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/resource-loader' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/browser/Window' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level1/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/events' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/html' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/languages/javascript' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level2/style' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/core' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/ls' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/level3/xpath' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/attributes' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/attributes/Attr-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/blob-symbols' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/blob' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/character-data' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/comment' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/document-type' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/document' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/dom-implementation' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/dom-token-list' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/element' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/CustomEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/ErrorEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/Event-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/EventTarget-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/HashChangeEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/KeyboardEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/MessageEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/MouseEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/MutationEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/ProgressEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/TouchEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/events/UIEvent-impl' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/file-reader' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/file-symbols' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/file' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/filelist-symbols' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/filelist' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/form-data-symbols' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/form-data' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/Attr' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/CustomEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/CustomEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/ErrorEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/ErrorEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/Event' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/EventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/EventModifierInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/EventTarget' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/HashChangeEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/HashChangeEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/HTMLTemplateElement' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/idl-utils' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/KeyboardEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/KeyboardEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/MessageEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/MessageEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/MouseEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/MouseEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/MutationEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/ProgressEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/ProgressEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/TouchEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/UIEvent' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/UIEventInit' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/generated/utils' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/document-base-url' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/internal-constants' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/ordered-set-parser' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/proxied-window-event-handlers' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/runtime-script-errors' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/helpers/validate-names' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/html-collection' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/index' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/named-properties-window' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-filter' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-iterator' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-list' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node-type' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/non-document-type-child-node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/parent-node' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/post-message' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/processing-instruction' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/selectors' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/text' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/url' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/xhr-sync-worker' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/xhr-utils' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/xmlhttprequest-event-target' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/xmlhttprequest-symbols' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/xmlhttprequest-upload' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/living/xmlhttprequest' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/named-properties-tracker' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/utils' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/virtual-console' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/vm-shim' {
  declare module.exports: any;
}

declare module 'jsdom/lib/jsdom/web-idl/DOMException' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsdom/lib/jsdom.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom'>;
}
declare module 'jsdom/lib/jsdom/browser/default-stylesheet.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/default-stylesheet'>;
}
declare module 'jsdom/lib/jsdom/browser/documentAdapter.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/documentAdapter'>;
}
declare module 'jsdom/lib/jsdom/browser/documentfeatures.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/documentfeatures'>;
}
declare module 'jsdom/lib/jsdom/browser/domtohtml.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/domtohtml'>;
}
declare module 'jsdom/lib/jsdom/browser/history.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/history'>;
}
declare module 'jsdom/lib/jsdom/browser/htmltodom.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/htmltodom'>;
}
declare module 'jsdom/lib/jsdom/browser/location.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/location'>;
}
declare module 'jsdom/lib/jsdom/browser/not-implemented.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/not-implemented'>;
}
declare module 'jsdom/lib/jsdom/browser/resource-loader.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/resource-loader'>;
}
declare module 'jsdom/lib/jsdom/browser/Window.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/browser/Window'>;
}
declare module 'jsdom/lib/jsdom/level1/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level1/core'>;
}
declare module 'jsdom/lib/jsdom/level2/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/core'>;
}
declare module 'jsdom/lib/jsdom/level2/events.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/events'>;
}
declare module 'jsdom/lib/jsdom/level2/html.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/html'>;
}
declare module 'jsdom/lib/jsdom/level2/languages/javascript.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/languages/javascript'>;
}
declare module 'jsdom/lib/jsdom/level2/style.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level2/style'>;
}
declare module 'jsdom/lib/jsdom/level3/core.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/core'>;
}
declare module 'jsdom/lib/jsdom/level3/ls.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/ls'>;
}
declare module 'jsdom/lib/jsdom/level3/xpath.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/level3/xpath'>;
}
declare module 'jsdom/lib/jsdom/living/attributes.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/attributes'>;
}
declare module 'jsdom/lib/jsdom/living/attributes/Attr-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/attributes/Attr-impl'>;
}
declare module 'jsdom/lib/jsdom/living/blob-symbols.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/blob-symbols'>;
}
declare module 'jsdom/lib/jsdom/living/blob.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/blob'>;
}
declare module 'jsdom/lib/jsdom/living/character-data.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/character-data'>;
}
declare module 'jsdom/lib/jsdom/living/comment.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/comment'>;
}
declare module 'jsdom/lib/jsdom/living/document-type.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/document-type'>;
}
declare module 'jsdom/lib/jsdom/living/document.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/document'>;
}
declare module 'jsdom/lib/jsdom/living/dom-implementation.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/dom-implementation'>;
}
declare module 'jsdom/lib/jsdom/living/dom-token-list.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/dom-token-list'>;
}
declare module 'jsdom/lib/jsdom/living/element.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/element'>;
}
declare module 'jsdom/lib/jsdom/living/events/CustomEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/CustomEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/ErrorEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/ErrorEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/Event-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/Event-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/EventTarget-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/EventTarget-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/HashChangeEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/HashChangeEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/KeyboardEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/KeyboardEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/MessageEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/MessageEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/MouseEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/MouseEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/MutationEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/MutationEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/ProgressEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/ProgressEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/TouchEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/TouchEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/events/UIEvent-impl.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/events/UIEvent-impl'>;
}
declare module 'jsdom/lib/jsdom/living/file-reader.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/file-reader'>;
}
declare module 'jsdom/lib/jsdom/living/file-symbols.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/file-symbols'>;
}
declare module 'jsdom/lib/jsdom/living/file.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/file'>;
}
declare module 'jsdom/lib/jsdom/living/filelist-symbols.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/filelist-symbols'>;
}
declare module 'jsdom/lib/jsdom/living/filelist.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/filelist'>;
}
declare module 'jsdom/lib/jsdom/living/form-data-symbols.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/form-data-symbols'>;
}
declare module 'jsdom/lib/jsdom/living/form-data.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/form-data'>;
}
declare module 'jsdom/lib/jsdom/living/generated/Attr.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/Attr'>;
}
declare module 'jsdom/lib/jsdom/living/generated/CustomEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/CustomEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/CustomEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/CustomEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/ErrorEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/ErrorEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/ErrorEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/ErrorEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/Event.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/Event'>;
}
declare module 'jsdom/lib/jsdom/living/generated/EventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/EventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/EventModifierInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/EventModifierInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/EventTarget.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/EventTarget'>;
}
declare module 'jsdom/lib/jsdom/living/generated/HashChangeEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/HashChangeEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/HashChangeEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/HashChangeEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/HTMLTemplateElement.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/HTMLTemplateElement'>;
}
declare module 'jsdom/lib/jsdom/living/generated/idl-utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/idl-utils'>;
}
declare module 'jsdom/lib/jsdom/living/generated/KeyboardEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/KeyboardEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/KeyboardEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/KeyboardEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/MessageEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/MessageEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/MessageEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/MessageEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/MouseEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/MouseEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/MouseEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/MouseEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/MutationEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/MutationEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/ProgressEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/ProgressEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/ProgressEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/ProgressEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/TouchEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/TouchEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/UIEvent.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/UIEvent'>;
}
declare module 'jsdom/lib/jsdom/living/generated/UIEventInit.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/UIEventInit'>;
}
declare module 'jsdom/lib/jsdom/living/generated/utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/generated/utils'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/document-base-url.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/document-base-url'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/internal-constants.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/internal-constants'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/ordered-set-parser.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/ordered-set-parser'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/proxied-window-event-handlers.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/proxied-window-event-handlers'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/runtime-script-errors.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/runtime-script-errors'>;
}
declare module 'jsdom/lib/jsdom/living/helpers/validate-names.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/helpers/validate-names'>;
}
declare module 'jsdom/lib/jsdom/living/html-collection.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/html-collection'>;
}
declare module 'jsdom/lib/jsdom/living/index.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/index'>;
}
declare module 'jsdom/lib/jsdom/living/named-properties-window.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/named-properties-window'>;
}
declare module 'jsdom/lib/jsdom/living/node-filter.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-filter'>;
}
declare module 'jsdom/lib/jsdom/living/node-iterator.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-iterator'>;
}
declare module 'jsdom/lib/jsdom/living/node-list.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-list'>;
}
declare module 'jsdom/lib/jsdom/living/node-type.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node-type'>;
}
declare module 'jsdom/lib/jsdom/living/node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/node'>;
}
declare module 'jsdom/lib/jsdom/living/non-document-type-child-node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/non-document-type-child-node'>;
}
declare module 'jsdom/lib/jsdom/living/parent-node.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/parent-node'>;
}
declare module 'jsdom/lib/jsdom/living/post-message.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/post-message'>;
}
declare module 'jsdom/lib/jsdom/living/processing-instruction.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/processing-instruction'>;
}
declare module 'jsdom/lib/jsdom/living/selectors.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/selectors'>;
}
declare module 'jsdom/lib/jsdom/living/text.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/text'>;
}
declare module 'jsdom/lib/jsdom/living/url.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/url'>;
}
declare module 'jsdom/lib/jsdom/living/xhr-sync-worker.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/xhr-sync-worker'>;
}
declare module 'jsdom/lib/jsdom/living/xhr-utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/xhr-utils'>;
}
declare module 'jsdom/lib/jsdom/living/xmlhttprequest-event-target.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/xmlhttprequest-event-target'>;
}
declare module 'jsdom/lib/jsdom/living/xmlhttprequest-symbols.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/xmlhttprequest-symbols'>;
}
declare module 'jsdom/lib/jsdom/living/xmlhttprequest-upload.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/xmlhttprequest-upload'>;
}
declare module 'jsdom/lib/jsdom/living/xmlhttprequest.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/living/xmlhttprequest'>;
}
declare module 'jsdom/lib/jsdom/named-properties-tracker.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/named-properties-tracker'>;
}
declare module 'jsdom/lib/jsdom/utils.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/utils'>;
}
declare module 'jsdom/lib/jsdom/virtual-console.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/virtual-console'>;
}
declare module 'jsdom/lib/jsdom/vm-shim.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/vm-shim'>;
}
declare module 'jsdom/lib/jsdom/web-idl/DOMException.js' {
  declare module.exports: $Exports<'jsdom/lib/jsdom/web-idl/DOMException'>;
}
