// flow-typed signature: ae3c8ec6ac7f6872bf7ccfdaf9e95eb3
// flow-typed version: <<STUB>>/np_v^3.0.4/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'np'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'np' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'np/cli' {
  declare module.exports: any;
}

declare module 'np/lib/git' {
  declare module.exports: any;
}

declare module 'np/lib/prerequisite' {
  declare module.exports: any;
}

declare module 'np/lib/publish' {
  declare module.exports: any;
}

declare module 'np/lib/ui' {
  declare module.exports: any;
}

declare module 'np/lib/util' {
  declare module.exports: any;
}

declare module 'np/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'np/cli.js' {
  declare module.exports: $Exports<'np/cli'>;
}
declare module 'np/index' {
  declare module.exports: $Exports<'np'>;
}
declare module 'np/index.js' {
  declare module.exports: $Exports<'np'>;
}
declare module 'np/lib/git.js' {
  declare module.exports: $Exports<'np/lib/git'>;
}
declare module 'np/lib/prerequisite.js' {
  declare module.exports: $Exports<'np/lib/prerequisite'>;
}
declare module 'np/lib/publish.js' {
  declare module.exports: $Exports<'np/lib/publish'>;
}
declare module 'np/lib/ui.js' {
  declare module.exports: $Exports<'np/lib/ui'>;
}
declare module 'np/lib/util.js' {
  declare module.exports: $Exports<'np/lib/util'>;
}
declare module 'np/lib/version.js' {
  declare module.exports: $Exports<'np/lib/version'>;
}
