// flow-typed signature: 9781adcda4d8236cf89d55cdeaa5bc1b
// flow-typed version: <<STUB>>/react-storybook-addon-add-stories-group_v0.1.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-storybook-addon-add-stories-group'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-storybook-addon-add-stories-group' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-storybook-addon-add-stories-group/dist/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-add-stories-group/example/ErrorBar' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-add-stories-group/example/story' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-add-stories-group/src/index' {
  declare module.exports: any;
}

declare module 'react-storybook-addon-add-stories-group/src/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-storybook-addon-add-stories-group/dist/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-add-stories-group/dist/index'>;
}
declare module 'react-storybook-addon-add-stories-group/example/ErrorBar.js' {
  declare module.exports: $Exports<'react-storybook-addon-add-stories-group/example/ErrorBar'>;
}
declare module 'react-storybook-addon-add-stories-group/example/story.js' {
  declare module.exports: $Exports<'react-storybook-addon-add-stories-group/example/story'>;
}
declare module 'react-storybook-addon-add-stories-group/src/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-add-stories-group/src/index'>;
}
declare module 'react-storybook-addon-add-stories-group/src/tests/index.js' {
  declare module.exports: $Exports<'react-storybook-addon-add-stories-group/src/tests/index'>;
}
