// flow-typed signature: 252c29bb09ee8469e88f604a1b78ddb3
// flow-typed version: <<STUB>>/reactman_v2.1.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reactman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reactman' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reactman/bin/reactman' {
  declare module.exports: any;
}

declare module 'reactman/test/templates/template-test' {
  declare module.exports: any;
}

declare module 'reactman/test/templates/template' {
  declare module.exports: any;
}

declare module 'reactman/test/templates/template.old' {
  declare module.exports: any;
}

declare module 'reactman/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reactman/bin/reactman.js' {
  declare module.exports: $Exports<'reactman/bin/reactman'>;
}
declare module 'reactman/test/templates/template-test.js' {
  declare module.exports: $Exports<'reactman/test/templates/template-test'>;
}
declare module 'reactman/test/templates/template.jsx' {
  declare module.exports: $Exports<'reactman/test/templates/template'>;
}
declare module 'reactman/test/templates/template.old.jsx' {
  declare module.exports: $Exports<'reactman/test/templates/template.old'>;
}
declare module 'reactman/test/test.js' {
  declare module.exports: $Exports<'reactman/test/test'>;
}
