// flow-typed signature: 81e51b0df66c058b4b177bd2bd469bdd
// flow-typed version: <<STUB>>/theo_v^6.0.0/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'theo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'theo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'theo/bin/scripts/build' {
  declare module.exports: any;
}

declare module 'theo/bin/theo' {
  declare module.exports: any;
}

declare module 'theo/lib/constants' {
  declare module.exports: any;
}

declare module 'theo/lib/definition' {
  declare module.exports: any;
}

declare module 'theo/lib/effects' {
  declare module.exports: any;
}

declare module 'theo/lib/formats/android.xml' {
  declare module.exports: any;
}

declare module 'theo/lib/formats/aura.tokens' {
  declare module.exports: any;
}

declare module 'theo/lib/formats/html' {
  declare module.exports: any;
}

declare module 'theo/lib/formats/ios.json' {
  declare module.exports: any;
}

declare module 'theo/lib/formats/json' {
  declare module.exports: any;
}

declare module 'theo/lib/formats/raw.json' {
  declare module.exports: any;
}

declare module 'theo/lib/index' {
  declare module.exports: any;
}

declare module 'theo/lib/register' {
  declare module.exports: any;
}

declare module 'theo/lib/transforms/color' {
  declare module.exports: any;
}

declare module 'theo/lib/transforms/number' {
  declare module.exports: any;
}

declare module 'theo/lib/transforms/unit' {
  declare module.exports: any;
}

declare module 'theo/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'theo/bin/scripts/build.js' {
  declare module.exports: $Exports<'theo/bin/scripts/build'>;
}
declare module 'theo/bin/theo.js' {
  declare module.exports: $Exports<'theo/bin/theo'>;
}
declare module 'theo/lib/constants.js' {
  declare module.exports: $Exports<'theo/lib/constants'>;
}
declare module 'theo/lib/definition.js' {
  declare module.exports: $Exports<'theo/lib/definition'>;
}
declare module 'theo/lib/effects.js' {
  declare module.exports: $Exports<'theo/lib/effects'>;
}
declare module 'theo/lib/formats/android.xml.js' {
  declare module.exports: $Exports<'theo/lib/formats/android.xml'>;
}
declare module 'theo/lib/formats/aura.tokens.js' {
  declare module.exports: $Exports<'theo/lib/formats/aura.tokens'>;
}
declare module 'theo/lib/formats/html.js' {
  declare module.exports: $Exports<'theo/lib/formats/html'>;
}
declare module 'theo/lib/formats/ios.json.js' {
  declare module.exports: $Exports<'theo/lib/formats/ios.json'>;
}
declare module 'theo/lib/formats/json.js' {
  declare module.exports: $Exports<'theo/lib/formats/json'>;
}
declare module 'theo/lib/formats/raw.json.js' {
  declare module.exports: $Exports<'theo/lib/formats/raw.json'>;
}
declare module 'theo/lib/index.js' {
  declare module.exports: $Exports<'theo/lib/index'>;
}
declare module 'theo/lib/register.js' {
  declare module.exports: $Exports<'theo/lib/register'>;
}
declare module 'theo/lib/transforms/color.js' {
  declare module.exports: $Exports<'theo/lib/transforms/color'>;
}
declare module 'theo/lib/transforms/number.js' {
  declare module.exports: $Exports<'theo/lib/transforms/number'>;
}
declare module 'theo/lib/transforms/unit.js' {
  declare module.exports: $Exports<'theo/lib/transforms/unit'>;
}
declare module 'theo/lib/util.js' {
  declare module.exports: $Exports<'theo/lib/util'>;
}
