version: 2.0

defaultRestoreCachedModules: &defaultRestoreCachedModules
  restore_cache:
    name: Restore cached node_modules
    keys:
      - v1-dependencies-{{ checksum "package-lock.json" }}

defaultNpmInstall: &defaultNpmInstall
  run:
    name: Install dependencies
    # only run npm ci if node_modules doesn't exist, as it clears
    # out node_modules and installs everything from scratch,
    # removing the benefit from using circle's caching
    command: |
      if [ ! -d node_modules ]; then
        npm ci
      fi

defaultCacheModules: &defaultCacheModules
  save_cache:
    name: Save node_modules cache
    paths:
      - node_modules
    key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  lint:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout

      - <<: *defaultRestoreCachedModules
      - <<: *defaultNpmInstall
      - <<: *defaultCacheModules

      - run: npm run lint

  test:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout

      - <<: *defaultRestoreCachedModules
      - <<: *defaultNpmInstall
      - <<: *defaultCacheModules

      - run: npm run test -- --coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
