// flow-typed signature: d2a0e7cebf8350ca06b799838f0a9419
// flow-typed version: <<STUB>>/@kalo/eslint-config_v6.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kalo/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kalo/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kalo/eslint-config/__tests__/test-rules' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kalo/eslint-config/__tests__/test-rules.js' {
  declare module.exports: $Exports<'@kalo/eslint-config/__tests__/test-rules'>;
}
declare module '@kalo/eslint-config/index' {
  declare module.exports: $Exports<'@kalo/eslint-config'>;
}
declare module '@kalo/eslint-config/index.js' {
  declare module.exports: $Exports<'@kalo/eslint-config'>;
}
