global:
  type: font-size
  category: typography
props:
  FONT_SIZE_HEADING_LARGE:
    value: 32px
  FONT_SIZE_HEADING_MEDIUM:
    value: 24px
  FONT_SIZE_HEADING_SMALL:
    value: 16px
  FONT_SIZE_HEADING_X_SMALL:
    value: 12px
  FONT_SIZE_TEXT_LARGE:
    value: 18px
  FONT_SIZE_TEXT_MEDIUM:
    value: 16px
  FONT_SIZE_TEXT_SMALL:
    value: 14px
  FONT_SIZE_TEXT_X_SMALL:
    value: 12px
