global:
  type: font-size
  category: typography
props:
  FONT_SIZE_HEADING_EXTRA_LARGE:
    value: 2.4rem
  FONT_SIZE_HEADING_LARGE:
    value: 2rem
  FONT_SIZE_HEADING_MEDIUM:
    value: 1.6rem
  FONT_SIZE_HEADING_SMALL:
    value: 1.4rem
  FONT_SIZE_HEADING_EXTRA_SMALL:
    value: 1rem
  FONT_SIZE_TEXT_EXTRA_LARGE:
    value: 2.4rem
  FONT_SIZE_TEXT_LARGE:
    value: 1.8rem
  FONT_SIZE_TEXT_MEDIUM:
    value: 1.6rem
  FONT_SIZE_TEXT_SMALL:
    value: 1.4rem
  FONT_SIZE_TEXT_EXTRA_SMALL:
    value: 1.2rem
