global:
  type: 'font-weight'
  category: 'typography'
props:
  FONT_WEIGHT_LIGHT:
    value: '300'
  FONT_WEIGHT_NORMAL:
    value: '400'
  FONT_WEIGHT_MEDIUM:
    value: '500'
  FONT_WEIGHT_SEMIBOLD:
    value: '600'