// flow-typed signature: fd2c07d09784e3b7223243e350e70533
// flow-typed version: <<STUB>>/@storybook/cli_v3.0.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/cli/bin/generate' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/METEOR/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/addons' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/template/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/template/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/REACT/template/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/Button' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/index' {
  declare module.exports: any;
}

declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/detect' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/has_yarn' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/helpers' {
  declare module.exports: any;
}

declare module '@storybook/cli/lib/project_types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/cli/bin/generate.js' {
  declare module.exports: $Exports<'@storybook/cli/bin/generate'>;
}
declare module '@storybook/cli/generators/METEOR/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/METEOR/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/addons'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE_SCRIPTS/template/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/addons.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/addons'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.android'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Button/index.ios'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/CenterView/style'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/index'>;
}
declare module '@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_NATIVE/template/storybook/stories/Welcome/index'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/index'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/Button'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/index'>;
}
declare module '@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT_SCRIPTS/template/src/stories/Welcome'>;
}
declare module '@storybook/cli/generators/REACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/index'>;
}
declare module '@storybook/cli/generators/REACT/template/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/template/stories/Button'>;
}
declare module '@storybook/cli/generators/REACT/template/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/template/stories/index'>;
}
declare module '@storybook/cli/generators/REACT/template/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/REACT/template/stories/Welcome'>;
}
declare module '@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/UPDATE_PACKAGE_ORGANIZATIONS/index'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/index'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/Button.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/template/stories/Button'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/index.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/template/stories/index'>;
}
declare module '@storybook/cli/generators/WEBPACK_REACT/template/stories/Welcome.js' {
  declare module.exports: $Exports<'@storybook/cli/generators/WEBPACK_REACT/template/stories/Welcome'>;
}
declare module '@storybook/cli/lib/detect.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/detect'>;
}
declare module '@storybook/cli/lib/has_yarn.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/has_yarn'>;
}
declare module '@storybook/cli/lib/helpers.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/helpers'>;
}
declare module '@storybook/cli/lib/project_types.js' {
  declare module.exports: $Exports<'@storybook/cli/lib/project_types'>;
}
